// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessRule struct {
	ID        string           `json:"id"`
	Ptype     pgtype.Text      `json:"ptype"`
	V0        pgtype.Text      `json:"v0"`
	V1        pgtype.Text      `json:"v1"`
	V2        pgtype.Text      `json:"v2"`
	V3        pgtype.Text      `json:"v3"`
	V4        pgtype.Text      `json:"v4"`
	V5        pgtype.Text      `json:"v5"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
